# Generated by Django 5.2.1 on 2025-10-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_meal_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('小', '幸福度：小'), ('primary', 'low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('小', '幸福度：小'), ('primary', 'low')], max_length=50),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('小', '幸福度：小'), ('primary', 'low')], max_length=50),
        ),
    ]
