# Generated by Django 5.2.1 on 2025-10-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_meal_priority_alter_product_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(default='朝食', max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='priority',
            field=models.CharField(choices=[('大', '幸福度：大'), ('中', '幸福度：中'), ('小', '幸福度：小')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='priority',
            field=models.CharField(choices=[('大', '幸福度：大'), ('中', '幸福度：中'), ('小', '幸福度：小')], max_length=50),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('大', '幸福度：大'), ('中', '幸福度：中'), ('小', '幸福度：小')], max_length=50),
        ),
    ]
