# Generated by Django 5.2.1 on 2025-10-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_meal_category_alter_meal_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(default='１日の食事', max_length=20),
        ),
    ]
